{% set name = "clipboard" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/clipboard-{{ version }}.tar.gz
  sha256: a72a78e9c9bf68da1c3f29ee022417d13ec9e3824b511559fd2b702b1dd5b817

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=2.7
    - pip
  run:
    - python >=2.7
    - pyperclip >=1.3

test:
  imports:
    - clipboard
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/terryyin/clipboard
  summary: A cross platform clipboard operation library of Python. Works for Windows, Mac and Linux.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
